title: Elias Portfolio
profile_img: /assets/img/Multimedia.jpg
icon_img: /assets/img/icon.webp

name: "Elías Halloumi El Amraoui"
job: "〈Estudiante〉"

phone_number: 631098391
address: Torrelavega, España
email: ehalloumie01@educantabria.es
linkedin_username: eliasxvv16 
github_username: eliasxvv16
instagram_username: elias.x16
twitter_username: eliasxvv16
facebook_username: eliasxvv16
youtube_username: eliasxvv16
blog_url: homepage-url

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
